# ref: https://docs.github.com/en/actions/tutorials/publish-packages/publish-docker-images#publishing-images-to-github-packages
# ref: https://github.com/ublue-os/boxkit/tree/main
name: Build and publish all container images

on:
  schedule:
  - cron: 0 7 * * *
  push:
    branches: [main, dev]
    # Publish semver tags as releases.
    tags: [v*.*.*]
     # don't rebuild if only documentation has changed
    paths-ignore: ['**.md']
  pull_request:
    branches: [main]
  workflow_dispatch:

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  distrobox-conatiner-images:
    name: Build and push distrobox container images
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    strategy:
      matrix:
        image-name:
        - cider-arch
        - cider-debian
        - cider-fedora
        - dev-arch
        - dev-fedora
        - emacs-alpine
        - emacs-arch
        - emacs-fedora
        - emacs-opensuse
        - latex-alpine
        - latex-arch
        - latex-fedora
        platform:
        - linux/amd64
          # - linux/arm/v6
          # - linux/arm/v7
          # - linux/arm64
      fail-fast: false
    uses: ./.github/workflows/build_and_publish_one_image.yml
    with:
      image-name: ${{ matrix.image-name }}
      containerfile: ./containerfiles/${{ matrix.image-name }}.containerfile
      context: ./context
      platform: ${{ matrix.platform }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}

  secureblue-images:
    name: Build and push secureblue container images
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    strategy:
      matrix:
        image-name:
        - cosmic-main-hardened
        - cosmic-nvidia-hardened
        - silverblue-main-hardened
        - silverblue-nvidia-hardened
        platform:
        - linux/amd64
          # - linux/arm/v6
          # - linux/arm/v7
          # - linux/arm64
      fail-fast: false
    uses: ./.github/workflows/build_and_publish_one_image.yml
    with:
      image-name: ${{ matrix.image-name }}
      containerfile: ./containerfiles/${{ matrix.image-name }}.containerfile
      context: ./context
      platform: ${{ matrix.platform }}
      slsa-verify-source: github.com/secureblue/secureblue
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
